# Testing with approximately 1k words

./client $(ps | grep ./server | awk 'NR==1{print $1}') "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque felis ligula, tincidunt sed convallis at, venenatis sit amet nisi. Ut dictum tristique finibus. Praesent tincidunt aliquet ex, et luctus massa dictum in. Sed aliquam et orci nec efficitur. Etiam scelerisque lacinia felis, sit amet malesuada ex consectetur eget. Integer felis dolor, efficitur vitae dui eu, tincidunt blandit erat. In dignissim venenatis maximus. Nam et efficitur turpis. Integer tincidunt, tortor ac elementum condimentum, sapien lacus rutrum mauris, in pharetra arcu tortor in nunc.

Nulla luctus felis in mi feugiat, quis sagittis turpis hendrerit. Sed vestibulum efficitur tortor at semper. Etiam blandit semper quam, a aliquet quam malesuada a. Aliquam aliquam tempus rhoncus. Morbi porta imperdiet pellentesque. Vivamus massa neque, tempus ut condimentum at, gravida non eros. Phasellus non fringilla arcu. Etiam auctor finibus tellus, a venenatis risus tincidunt eget.

Fusce placerat in orci sed faucibus. Nulla lacus ipsum, viverra vitae ligula sed, tempus varius nunc. Suspendisse potenti. In vehicula tincidunt urna sit amet viverra. Phasellus quis metus pretium, tempus sem non, ultricies mi. Pellentesque feugiat ligula quis turpis ultrices congue. Maecenas dignissim ipsum et neque vehicula iaculis.

Ut interdum dui vel sagittis euismod. Sed vitae egestas lorem. Sed sit amet massa sed augue aliquam ultricies vel at ipsum. Proin eu volutpat enim. In porta fermentum turpis vel fermentum. Vivamus nec posuere sem. Morbi vel placerat tellus.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In non orci vitae risus lobortis iaculis vel non sem. Ut suscipit felis ipsum, vel fringilla nisi congue sit amet. Ut nunc nulla, lacinia nec eros id, bibendum ullamcorper ex. Nunc commodo mi in nunc congue, vitae blandit sapien aliquet. Sed bibendum nibh nec justo viverra consequat. Nullam vel tempor augue. Nam eu quam augue. Phasellus vitae nulla convallis, fermentum ex non, auctor ipsum. Ut varius, sapien in consectetur eleifend, dui dolor molestie massa, vel volutpat velit elit eget sem.

Aliquam tincidunt ipsum ac tincidunt fermentum. Morbi ac pellentesque lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed in tincidunt massa. Duis ultrices, sem vel interdum pharetra, lectus magna vehicula elit, at hendrerit sapien dolor a risus. Quisque fermentum elit lacinia turpis ultricies, nec accumsan est egestas. Vivamus mollis placerat erat, eget elementum elit ullamcorper a.

Nullam ac vulputate augue. Sed tempor, eros vel convallis mattis, elit velit molestie lacus, non volutpat eros tellus dignissim purus. Ut non interdum nibh. Cras ullamcorper consectetur tellus sit amet convallis. Donec suscipit dapibus vulputate. Aenean aliquam augue vitae mi molestie venenatis. Aliquam viverra, arcu at mattis imperdiet, quam sapien blandit ex, eu ultrices magna libero a mi. Mauris varius at tellus a placerat. Ut eget lorem urna. Sed justo tellus, tincidunt elementum rutrum pharetra, ultrices elementum tellus. Maecenas scelerisque lectus enim, vitae pretium nisi condimentum quis. Suspendisse vel augue imperdiet, feugiat enim sed, venenatis dolor. Nam elit quam, dapibus nec diam vitae, commodo rhoncus risus. Ut ornare sed elit tempor ultricies. Etiam dignissim, sapien non imperdiet facilisis, ipsum lacus viverra est, non blandit est quam quis magna.

Morbi vehicula dignissim ipsum vel consectetur. Morbi vel dolor vitae nisl interdum placerat vitae eget lorem. Phasellus ac felis a libero pulvinar auctor a sed justo. Proin luctus, metus vitae fermentum commodo, lorem dolor dictum turpis, ac rhoncus dui diam non velit. Nunc sit amet porta diam, sed placerat leo. Phasellus ultricies ultricies diam, sit amet commodo arcu posuere in. Donec non tellus dui.

Pellentesque non felis eu augue pretium tincidunt eget sit amet ligula. In ac leo sed odio tempor ultricies. Fusce tempus lectus in nibh pretium feugiat. Etiam finibus, lectus at aliquam elementum, dolor neque vehicula purus, ac dapibus dolor leo id ligula. Integer sem orci, ultricies vitae varius ut, ultricies sed nibh. Sed quam eros, hendrerit sed quam vel, posuere fringilla leo. Integer porttitor justo id blandit consectetur. Phasellus congue ipsum a nunc porta, eu eleifend felis feugiat. Suspendisse sodales vulputate lorem vitae suscipit. Phasellus sit amet massa sed velit aliquet fringilla. Praesent posuere purus sem, id sollicitudin nunc porttitor vitae. Morbi vitae justo vitae ex ullamcorper eleifend. Proin luctus erat id cursus iaculis. Maecenas sagittis ornare mi, mollis malesuada mi condimentum non.

Mauris sem eros, suscipit non est nec, mollis imperdiet elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam vulputate mollis justo id ullamcorper. Curabitur congue et velit a dignissim. Nulla dignissim felis mauris, in placerat risus efficitur vel. Nullam elit tellus, facilisis ac erat pellentesque, cursus auctor massa. Pellentesque dapibus, lacus non viverra iaculis, neque tortor semper quam, at molestie quam dui luctus mi. Aenean a mattis nulla. Aenean facilisis ipsum quam, quis mollis ante fermentum sit amet. Nam lacus magna, pellentesque sed ligula vehicula, tempor placerat ex. Phasellus augue orci, interdum vitae nisi et, malesuada sagittis elit. Nunc egestas magna non hendrerit tempor. In sodales risus lacus, vel condimentum lectus dignissim a. Duis quis rutrum ipsum. Cras iaculis ac erat vitae vestibulum. Aliquam erat volutpat.

Phasellus feugiat mauris nisi, a pretium diam feugiat id. Curabitur quis lacus condimentum tortor mollis interdum. Duis tempor vel ligula ut placerat. Nullam sit amet sem lectus. Vestibulum molestie sapien at nulla convallis vulputate. Morbi dignissim, dui venenatis placerat finibus, tortor magna aliquet est, eget vehicula orci neque nec ligula. Aenean ultrices, justo eget dignissim vestibulum, tellus eros ullamcorper sapien, sed convallis sem leo nec lectus. Morbi vel gravida enim. Sed a lorem sed augue pulvinar sagittis id sit amet turpis. Nunc volutpat porttitor lacus, at elementum quam lobortis non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam velit nisi, auctor vitae felis et, pellentesque lobortis nulla. Etiam consequat, enim et lobortis vestibulum, dui purus imperdiet ipsum, ac imperdiet turpis tellus et odio. Morbi massa felis, finibus ut velit sit amet, tincidunt maximus leo. Maecenas dui diam, iaculis id ullamcorper at, imperdiet ac ante. Mauris in pretium lorem.

Duis mattis nisi at urna condimentum imperdiet. Duis vel tortor velit. Ut consequat ipsum non nisl volutpat, id aliquet arcu lobortis."